name: CI

on:
  push:
    branches-ignore:
        - main
  pull_request:

jobs:
  terrafrom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0
      
      - name: Terraform Init
        working-directory: terraform/env/dev
        run: terraform init -backend=false

      - name: formatting terraform code
        working-directory: terraform/env/dev
        run: terraform fmt -check
        
      - name: checking the code
        working-directory: terraform/env/dev
        run: terraform validate
    
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Validate K8s manifests
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: '/kubeconform'
          args: "-summary -output text k8s/"
